#ifndef _CTIOT_DEVICE_INFO_H
#define _CTIOT_DEVICE_INFO_H

#define DEVICE_NO "0001"
#define DEVICE_ID "100066080001"
#define DEVICE_PROTOCOL "MQTT"
#define DEVICE_AUTHORIZATION "token"
#define DEVICE_TOKEN "mgdCh5os52yzvVnvlLNPfCd1Mcobk4KF5BalaW0W1Fk"
#define DEVICE_TRANSPARENT 1
#define DEVICE_TCPADDRESS "mqtt.ctwing.cn"
#define DEVICE_TCPPORT "1883"
#define DEVICE_TLSADDRESS "mqtt.ctwing.cn"
#define DEVICE_TLSPORT "8883"

#endif //_CTIOT_DEVICE_INFO_H
